const typeData = {
  1: 'Weapons',
  2: 'Off-hand',
  3: 'Armors',
  4: 'Garments',
  5: 'Footgears',
  6: 'Accessory',
  7: 'Blueprint',
  8: 'Potion: /: Effect',
  9: 'Refine',
  10: 'Scroll: /: Album',
  11: 'Material',
  12: 'Holiday: material',
  13: 'Pet: material',
  14: 'Premium',
  15: 'Costume',
  16: 'Head',
  17: 'Face',
  18: 'Back',
  19: 'Mouth',
  20: 'Tail',
  21: 'Weapon: card',
  22: 'Off-hand: card',
  23: 'Armor: card',
  24: 'Garments: card',
  25: 'Shoe: card',
  26: 'Accessory: card',
  27: 'Headwear: card',
};
